\mainmatter

# Introducción 

## Plano Complejo

```{definition}
El plano complejo o cuerpo de un número complejo es el conjunto siguiente

\begin{equation}
\mathbb{C} =\{ (x,y) : x,y \in \mathbb R\}
\end{equation}

Con las operaciones

- Suma: $(x_1,y_1) + (x_2,y_2) = (x_1+x_2,y_1 +y_2)$.

- Producto escalar $\lambda (x,y) \ne (\lambda x,\lambda y)$

- Producto $(x_1,y_1) (x_2,y_2) = (x_1x_2 - y_1y_2,y_1 +y_2)$
```

Haciendo la identificación 

$$
\left \{ 
\begin{array}{rcl}
1 & = & (1,0)\\
0 & = & (0,1)
\end{array}
\right.
$$

Si $(x,y)\in \mathbb C$ entonces $(x,y)=x(1,0)+y(0,1)=x+iy$

Tenemos que

$$
\begin{array}{rcl}
i^2 & = & i i\\
& = & (0,1)(0,1)\\
& = & (0+i1)(0+i1)\\
& = & 0\times 0+ 0\times i1+ i1\times 0+ i1\times i1\\
& = & 0+ 0+ 0+ i \times i\\
& = & -1\\
& = & (-1,0)\\
i^2 & = & -1
\end{array}
$$

Y por otra parte

$$
\begin{array}{rcl}
(x_1,y_1) (x_2,y_2) & = & (x_1+iy_1)(x_2+iy_2)\\
& = & x_1 x_2 +  x_1 i y_2 + i y_1 x_2+ i^2 y_1 y_2\\
& = & x_1 x_2 +  i (x_1 y_2 + y_1 x_2) + i^2 y_1 y_2\\
& = & x_1 x_2 +  i (x_1 y_2 + y_1 x_2) - y_1 y_2\\
& = & x_1 x_2 - y_1 y_2 +  i (x_1 y_2 + y_1 x_2) \\
(x_1,y_1) (x_2,y_2) & = & (x_1 x_2 - y_1 y_2, x_1 y_2 + y_1 x_2)
\end{array}
$$

Representación del plano complejo

```{r, echo=FALSE}
data <- data.frame( x = 2, y = 4)

ggplot(data, aes(x,y, fill=y))+
  geom_curve( aes(x = 0, y = -0.5, xend = 0, yend = 5), arrow = arrow(length = unit(0.03, "npc")),curvature = 0, size=0.6)+
  geom_curve( aes(x = -0.5, y = 0, xend = 3, yend = 0), arrow = arrow(length = unit(0.03, "npc")),curvature = 0, size=0.6)+
  geom_curve( aes(x = 2, y = 0, xend = 2, yend = 4), curvature = 0, size=0.6, color="blue")+
  geom_curve( aes(x = 0, y = 4, xend = 2, yend = 4), curvature = 0, size=0.6, color="blue")+
  geom_point()+
  annotate( "text", x = 2.2, y = 4.2, col="black", label = paste("x+iy"), parse = TRUE, size=5)+ 
  annotate( "text", x = 2, y = -0.2, col="black", label = "x", parse = TRUE, size=5)+ 
  annotate( "text", x = -0.1, y = 4, col="black", label = "y", parse = TRUE, size=5)+ 
  annotate( "text", x = 3.1, y = 0, col="black", label = "R", parse = TRUE, size=5)+ 
  annotate( "text", x = 0, y = 5.2, col="black", label = "i", parse = TRUE, size=5)+ 
  guides(fill=FALSE)+
  theme( plot.title = element_text(face= "bold", colour= "black", size=10),
         axis.title.x=element_text(face= "bold", colour= "black", size=6),
         axis.title.y=element_text(face= "bold", colour= "black", size=6),
         axis.text.y=element_blank(), axis.ticks.y =element_blank(),
         axis.text.x=element_blank(), axis.ticks.x =element_blank())+
  labs(title = "Plano Complejo", x="Eje Real", y="Eje Imaginario")
```

De ahora en adelante denotaremos a cualquier número complejo $z\in \mathbb C$ como $z=x+iy$ donde $x,y \in \mathbb R$,  $x=\text{Re}(z)$ es la parte real y $y=\text{Im}(z)$ es la parte imaginaria.

```{definition}
El __modulo__ de un número complejo, se define como

$$|z|=(x^2+y^2)^{1/2}$$
```

Este nos representa el tamaño del vector que que tiene como origen el punto $(0,0)$ y destino el punto $(x,y)$.

```{definition}
El __conjugado__ de un número complejo $z=x+iy$, se define como

$$\overline{z}=x-iy$$
```

El conjugado de cualquier número complejo es el relejo con respecto al eje real.

## Proposiciones

Sean $z, w \in \mathbb{C}$, $z=(x_1, y_1)$, $w=(x_2, y_2)$ y $\mid z \mid = (x_1^2+y_1^2)^{\frac{1}{2}}$

```{proposition}
$\mid zw\mid = \mid z \mid \mid w\mid$
```

```{proof}
$$
\begin{array}{rcl}
\mid zw\mid & = & \mid (x_1, y_1)(x_2, y_2)\mid\\ 
 & = & \mid x_1x_2 + ix_1y_2 + iy_1x_2 - y_1y_2 \mid\\ 
 & = & \mid (x_1x_2 - y_1y_2 + ix_1y_2 + iy_1x_2) \mid\\ 
 & = & \mid (x_1x_2 - y_1y_2, x_1y_2 + y_1x_2) \mid\\ 
 & = & ( (x_1x_2 - y_1y_2)^2 + (x_1y_2 + y_1x_2)^2)^{\frac{1}{2}}\\ 
 & = & ( x_1^2x_2^2 - 2x_1x_2y_1y_2 + y_1^2y_2^2 + x_1^2y_2^2 + 2x_1y_2y_1x_2+ y_1^2x_2^2)^{\frac{1}{2}}\\ 
 & = & ( x_1^2(x_2^2+y_2^2) + y_1^2(x_2^2+y_2^2))^{\frac{1}{2}}\\ 
 & = & ( (x_1^2+y_1^2)(x_2^2+y_2^2))^{\frac{1}{2}}\\ 
 & = & (x_1^2+y_1^2)^{\frac{1}{2}}(x_2^2+y_2^2)^{\frac{1}{2}}\\  
\mid zw\mid & = & \mid z \mid \mid w\mid
\end{array}
$$
```

```{proposition}
$\mid z^n \mid = \mid z \mid^n$
```

```{proof}
Vamos a realizar la demostración por inducción, 

Para $n=2$

$$
\begin{array}{rcl}
\mid z^2 \mid & = & \mid z z \mid \\
 & = & \mid z \mid\mid z \mid \text{, por la propiedad anterior}\\
 & = & \mid z \mid^2 \\
\end{array}
$$

Supongamos que se cumple para $n=k$ que $\mid z^k \mid = \mid z \mid^k$

Para $n=k+1$

$$
\begin{array}{rcl}
\mid z^{k+1} \mid & = & \mid z^kz \mid \\
 & = & \mid z^kz \mid\\
 & = & \mid z^k\mid \mid z \mid \text{, por la proiedad anterior} \\
 & = & \mid z\mid^k \mid z \mid \text{, por la hipó tesis inductiva}\\
\mid z^{k+1} \mid & = & \mid z\mid^{k+1}
\end{array}
$$
```

```{proposition}
$z \bar{z} = \mid z \mid^2$
```

```{proof}
$$
\begin{array}{rcl}
z \bar{z} & = & (x+iy)(x-iy)\\
& = & x^2 -ixy +iyx - iy iy\\
& = & x^2 -ixy +ixy - i^2 y^2\\
& = & x^2 + y^2\\
& = & (x^2 + y^2)^{\frac{1}{2}\times 2}\\
& = & ([x^2 + y^2]^{\frac{1}{2}})^{2}\\
z \bar{z} & = & \mid z \mid^{2}
\end{array}
$$
```

```{proposition}
Sea $z\ne 0$, $\displaystyle \frac{1}{z} = \displaystyle \frac{\bar{z}}{\mid z \mid^2}$
```

```{proof}
$$
\begin{array}{rcl}  
\displaystyle \frac{1}{z} & = & \displaystyle \frac{\bar{z}}{\bar{z}}\frac{1}{z}\\
& = & \displaystyle \frac{\bar{z}}{\bar{z}z}\\
\displaystyle \frac{1}{z} & = & \displaystyle \frac{\bar{z}}{\mid z \mid^{2}} \quad \text{Por la porposició n anterior}
\end{array}
$$
```

## Representación Polar

```{definition}
Si $z=x+iy\in \mathbb C$, tiene una representación polar $(r,\theta)$ con $r\in \mathbb R^+$ y $\theta \in \mathbb R$ si 

$$
\begin{array}{rcl}
x & = & r \cos(\theta)\\
y & = & r \sin(\theta)
\end{array}
$$
```

```{definition}
El __argumento__ de $z$ es $\theta$. 
```

El argumento no es una función, es una función multivariada. Si $\theta=\text{Arg}(z)$ entonces $\forall n \in \mathbb Z$ $\theta+2\pi n$

$$\tan(\theta)=\frac{y}{x}$$

```{proposition}
Si $z_1,z_2,...,z_n \in \mathbb C$ entonces

$$\text{Arg}\left(\prod_{k=1}^n z_k\right)=\sum_{k=1}^n \text{Arg}(z_k)mod (2\pi)$$
```

```{proof}
Lo probaremos por inducción.

- Primero probemos que se cumple para $n=2$, supongamos que tenemos dos números complejos $z_1,z_2$ escribiremos su forma polar 


```

$$
z_1 =  \left\{ 
\begin{array}{rcl}
r_1 \cos(\theta_1) \\ r_1 \sin(\theta_1) 
\end{array}
\right.
$$

$$
z_2 = \left\{ 
\begin{array}{rcl}
r_2 \cos(\theta_2) \\ r_2 \sin(\theta_2) 
\end{array}
\right.
$$

Veamos cuanto nos da el productor de estos dos números complejos

$$
\begin{array}{rcl}
z_1 z_2 & = & 
\end{array}
$$